server:
  port: 8082
  use-forward-headers: true
  servlet:
    context-path: /ui
    session:
      cookie:
        path: UISESSION

security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: ClientId
      clientSercret: secret
      accessTokenUri: http://localhost:8081/auth/oauth/token
      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:8081/auth/rest/hello/principal

spring:
  thymeleaf:
    cache: false